package com.motadata.ipam.service;

import ar.com.fdvs.dj.core.DynamicJasperHelper;
import ar.com.fdvs.dj.core.layout.ClassicLayoutManager;
import ar.com.fdvs.dj.domain.DynamicReport;
import ar.com.fdvs.dj.domain.Style;
import ar.com.fdvs.dj.domain.builders.ColumnBuilder;
import ar.com.fdvs.dj.domain.builders.FastReportBuilder;
import ar.com.fdvs.dj.domain.constants.Font;

import com.motadata.ipam.dao.AlertDao;
import com.motadata.ipam.dao.DhcpDao;
import com.motadata.ipam.dao.EventDao;
import com.motadata.ipam.dao.SubnetDao;
import com.motadata.ipam.model.AlertStream;
import com.motadata.ipam.model.Event;
import com.motadata.ipam.model.SubnetDetails;

import io.vertx.core.Future;
import io.vertx.core.Promise;
import io.vertx.core.Vertx;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import org.slf4j.LoggerFactory;
import org.slf4j.Logger;

import java.io.ByteArrayOutputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * Asynchronous Vert.x Service for generating PDF Reports using DynamicJasper and OpenPDF.
 */
public class ReportService {

    private static final Logger LOGGER = LoggerFactory.getLogger(ReportService.class);

    static {
        System.setProperty("net.sf.jasperreports.awt.ignore.missing.font", "true");
    }

    private final Vertx vertx;
    private final SubnetDao subnetDao;
    private final AlertDao alertDao;
    private final EventDao eventDao;
    private final DhcpDao dhcpDao;

    public ReportService(Vertx vertx, SubnetDao subnetDao, AlertDao alertDao, EventDao eventDao, DhcpDao dhcpDao) {
        this.vertx = vertx;
        this.subnetDao = subnetDao;
        this.alertDao = alertDao;
        this.eventDao = eventDao;
        this.dhcpDao = dhcpDao;
    }

    public Future<byte[]> generateSubnetPdfReport() {
        Promise<byte[]> promise = Promise.promise();

        subnetDao.findAllSubnets().onComplete(ar -> {
            if (ar.succeeded()) {
                List<SubnetDetails> subnets = ar.result();
                executeBlockingReportGeneration("Subnet Utilization Report", subnets, createSubnetReportColumns())
                        .onComplete(promise);
            } else {
                LOGGER.error("Failed to fetch subnets for report: {}", ar.cause().getMessage());
                promise.fail(ar.cause());
            }
        });

        return promise.future();
    }

    public Future<byte[]> generateAlertPdfReport() {
        Promise<byte[]> promise = Promise.promise();

        alertDao.findByStatusOrderByTimestampDesc(true, 1, 100).onComplete(ar -> {
            if (ar.succeeded()) {
                List<AlertStream> alerts = ar.result();
                executeBlockingReportGeneration("Alert History Report", alerts, createAlertReportColumns())
                        .onComplete(promise);
            } else {
                LOGGER.error("Failed to fetch alerts for report: {}", ar.cause().getMessage());
                promise.fail(ar.cause());
            }
        });

        return promise.future();
    }

    public Future<byte[]> generateEventPdfReport() {
        Promise<byte[]> promise = Promise.promise();

        eventDao.findAllEvents(100, 0).onComplete(ar -> {
            if (ar.succeeded()) {
                List<Event> events = ar.result();
                executeBlockingReportGeneration("Event Audit Log Report", events, createEventReportColumns())
                        .onComplete(promise);
            } else {
                LOGGER.error("Failed to fetch events for report: {}", ar.cause().getMessage());
                promise.fail(ar.cause());
            }
        });

        return promise.future();
    }

    public Future<byte[]> generateDhcpPdfReport() {
        Promise<byte[]> promise = Promise.promise();

        dhcpDao.findAllCredentials().onComplete(ar -> {
            if (ar.succeeded()) {
                List<Map<String, Object>> dhcpServers = ar.result();
                executeBlockingReportGeneration("DHCP Server Statistics Report", dhcpServers, createDhcpReportColumns())
                        .onComplete(promise);
            } else {
                LOGGER.error("Failed to fetch DHCP credentials for report: {}", ar.cause().getMessage());
                promise.fail(ar.cause());
            }
        });

        return promise.future();
    }

    private <T> Future<byte[]> executeBlockingReportGeneration(String title, List<T> data, List<ReportColumnDef> columns) {
        Promise<byte[]> promise = Promise.promise();

        vertx.<byte[]>executeBlocking(blockingPromise -> {
            try {
                FastReportBuilder frb = new FastReportBuilder();
                frb.setTitle(title);
                frb.setSubtitle("Generated by Motadata IPAM System");
                frb.setUseFullPageWidth(true);

                Style defaultStyle = new Style();
                defaultStyle.setFont(new Font(9, "SansSerif", false));
                frb.setDefaultStyles(defaultStyle, defaultStyle, defaultStyle, defaultStyle);

                for (ReportColumnDef col : columns) {
                    frb.addColumn(ColumnBuilder.getNew()
                            .setColumnProperty(col.property, String.class.getName())
                            .setTitle(col.title)
                            .setWidth(col.width)
                            .setStyle(defaultStyle)
                            .build());
                }

                DynamicReport dynamicReport = frb.build();
                JRBeanCollectionDataSource dataSource = new JRBeanCollectionDataSource(data != null ? data : new ArrayList<>());

                JasperPrint jasperPrint = DynamicJasperHelper.generateJasperPrint(dynamicReport, new ClassicLayoutManager(), dataSource);

                ByteArrayOutputStream pdfOutputStream = new ByteArrayOutputStream();
                net.sf.jasperreports.engine.JasperExportManager.exportReportToPdfStream(jasperPrint, pdfOutputStream);

                blockingPromise.complete(pdfOutputStream.toByteArray());
            } catch (Exception e) {
                LOGGER.error("Error building DynamicJasper PDF report '{}': {}", title, e.getMessage(), e);
                blockingPromise.fail(e);
            }
        }, promise);

        return promise.future();
    }

    private List<ReportColumnDef> createSubnetReportColumns() {
        List<ReportColumnDef> cols = new ArrayList<>();
        cols.add(new ReportColumnDef("subnetAddress", "Subnet Address", 120));
        cols.add(new ReportColumnDef("subnetMask", "Subnet Mask", 100));
        cols.add(new ReportColumnDef("description", "Description", 150));
        cols.add(new ReportColumnDef("createdBy", "Created By", 90));
        return cols;
    }

    private List<ReportColumnDef> createAlertReportColumns() {
        List<ReportColumnDef> cols = new ArrayList<>();
        cols.add(new ReportColumnDef("message", "Alert Message", 180));
        cols.add(new ReportColumnDef("alertType", "Alert Type", 90));
        cols.add(new ReportColumnDef("subnet", "Subnet", 100));
        return cols;
    }

    private List<ReportColumnDef> createEventReportColumns() {
        List<ReportColumnDef> cols = new ArrayList<>();
        cols.add(new ReportColumnDef("eventType", "Event Type", 100));
        cols.add(new ReportColumnDef("eventContext", "Details / Context", 200));
        return cols;
    }

    private List<ReportColumnDef> createDhcpReportColumns() {
        List<ReportColumnDef> cols = new ArrayList<>();
        cols.add(new ReportColumnDef("credentialName", "Credential Name", 100));
        cols.add(new ReportColumnDef("hostAddress", "Host Address", 110));
        cols.add(new ReportColumnDef("type", "Type", 80));
        cols.add(new ReportColumnDef("createdBy", "Created By", 90));
        return cols;
    }

    private static class ReportColumnDef {
        final String property;
        final String title;
        final Integer width;

        ReportColumnDef(String property, String title, Integer width) {
            this.property = property;
            this.title = title;
            this.width = width;
        }
    }
}
