#
## OAuth Server Configure
#
version=4.0.0

refreshTokenValidity=300000000
accessTokenValidity=300000000

#
## View Configure
#
spring.mvc.view.prefix: /
spring.mvc.view.suffix: .jsp
server.error.whitelabel.enabled=true

server.use-forward-headers= true
server.tomcat.remote-ip-header=x-forwarded-for
server.tomcat.protocol-header=x-forwarded-proto

#
## File Configure
#
spring.http.multipart.max-file-size=60MB
spring.http.multipart.max-request-size=60MB

#
## Database Configure
#
spring.datasource.tomcat.max-wait = 2000000
spring.jpa.database: MYSQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.current_session_context_class=org.springframework.orm.hibernate5.SpringSessionContext

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
spring.jpa.properties.hibernate.naming_strategy = org.hibernate.cfg.ImprovedNamingStrategy
spring.jpa.properties.hibernate.type=trace
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration

spring.jpa.show-sql=true

spring.datasource.type = org.apache.tomcat.jdbc.pool.DataSource
spring.cache.type=simple
